name: openai_to_z          # keep it simple: no spaces
channels:
  - pytorch                # first so the correct torch build wins
  - conda-forge
  - defaults

dependencies:
  # ---------- core ----------
  - python=3.12
  - pip                     # makes sure pip itself is managed by conda

  # ---------- notebooks & dev ----------
  - jupyterlab=4
  - invoke
  - path.py
  - mlflow                  # conda build avoids protobuf clashes

  # ---------- data / viz stack ----------
  - numpy
  - pandas
  - pandas-profiling
  - matplotlib
  - seaborn
  - statsmodels
  - scikit-learn
  - lightgbm
  - rasterio
  - xgboost
  - folium

  # ---------- deep-learning frameworks ----------
  - pytorch=2.2.*           # CPU build from pytorch channel
  - torchvision=0.17.*
  - torchaudio=2.2.*
  - cpuonly                 # keeps CUDA stuff out; drop this on a GPU box

  - tensorflow=2.19.*       # CPU -only build from conda-forge

  # ---------- pip-only extras ----------
  - pip:
      - black
      - h2o
      - kaggle
      - keras               # optional – TF already bundles Keras 3
      - missingno
      - nbdime
      - plotly>=5
      - pylint
      - pyspark