name: openai_to_z               # no spaces = fewer headaches
channels:
  - conda-forge
  - defaults

dependencies:
  # ---------- core interpreter ----------
  - python=3.13                   # latest stable

  # ---------- dev & notebook stack ----------
  - jupyterlab=4
  - invoke
  - path.py
  - pip                           # pulls pip itself from conda
  - mlflow                        # conda build avoids protobuf clashes

  # ---------- scientific stack ----------
  - numpy
  - pandas
  - pandas-profiling
  - matplotlib
  - seaborn
  - statsmodels
  - scikit-learn
  - lightgbm

  # ---------- extras you’ll likely add soon ----------
  - rasterio                      # geospatial rasters
  - xgboost
  - folium

  # ---------- pip-only packages ----------
  - pip:
      - black
      - h2o
      - kaggle
      - keras                     # uses tf-keras 3.x under the hood
      - missingno
      - nbdime
      - plotly>=5
      - pylint
      - pyspark
      - tensorflow==2.16.*        # pin to latest long-term patch